theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  plausible: comnum.rennes.fr
  summary:
    position: content
  search:
    active: true
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/monogramme-blanc.svg"
  menu:
    primary:
      level_2:
        title:
          active: true
  debug:
    productionUrl: "https://comnum.rennes.fr"
  posts:
    index:
      show_categories: true
      show_description: true