theme: rennes-hugo-theme
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: comnum.rennes.fr
  summary:
    position: content
  search:
    active: true
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/monogramme-blanc.svg"
  menu:
    dropdown:
      linkToLevel1: true
  debug:
    productionUrl: "https://comnum.rennes.fr"